Main.java
src/week2/soram/COTE1181.java
src/week2/soram/COTE1371.java
src/week2/soram/COTE3447.java

Daily Commit

---

README.md
src/week3/hong/BoJ11655.java
src/week3/hong/BoJ11656.java

README.md update
🅰️ .URL edit [Space-> % Change]
========================================================
page1
Title : 11655 / ROT13
Date : Today (4th July 2022 year)
Level : BronzeⅠ
Success or False :  ✔️(Success)
========================================================
page2
Title : 11656 / 접미사 배열
Date : Today (4th July 2022 year)
Level : silver Ⅳ
Success or False :  ✔️(Success)

[DC] Daily Commit

---

src/week3/hong/IjC201.java

Edit Commit
🅰️ . numbering change  IjC113->IjC201

[EC] Edit Commit

---

src/week3/soram/BOJ11655.java
src/week3/soram/inflearn/code.java
src/week3/soram/inflearn/maxnum.java

220709 commit

---

src/week3/yumi/BoJ11655.java
src/week3/yumi/BoJ11656.java
src/week3/yumi/BoJ6571.java
src/week3/yumi/IjC204.java
src/week3/yumi/Prg60057.java

Creat IjC204.java, BoJ11655.java, BoJ11656.java, BoJ6571.java, Prg60057.java
Site : 인프런
Title : 2-4 / 피보나치 수열
Date : Today(8th July 2022 year)
Subject : 배열
Site : BOJ 백준 사이트
Title : 11655 / ROT13
Date : Today(9th July 2022 year)
Subject : 문자열
Site : BOJ 백준 사이트
Title : 11656 / 접미사 배열
Date : Today(9th July 2022 year)
Subject : 문자열, 배열 …

[Week3] Ijc204.java ~ commonProblems Commit

---

src/week3/soram/BOJ11656.java
src/week3/soram/StringCompression.java
src/week3/soram/fibonacci.java

220710 commit

---

src/week4/soram/IjC206.java
src/week4/soram/IjC207.java
src/week4/soram/IjC209.java
src/week4/soram/IjC210.java
src/week4/soram/ljC205.java
src/week4/soram/ljC208.java

220716 commit

---

src/week4/woojin/BoJ2477.java

Title : 2477 / 참외밭
Level : silver Ⅲ
Subject : Array

[김우진] BoJ 2477 참외밭

---

src/week4/soram/BOJ1783.java
src/week4/soram/IjC210.java
src/week5/soram/IjC211.java
src/week5/soram/IjC212.java
src/week5/soram/IjC301.java
src/week5/soram/IjC302.java
src/week5/soram/IjC303.java

20220721 commit

---

src/week5/yumi/BoJ10989.java
src/week5/yumi/BoJ1110.java
src/week5/yumi/IjC211.java
src/week5/yumi/IjC212.java
src/week5/yumi/IjC301.java

Create BoJ10989.java, BoJ1110.java, IjC211.java, IjC212.java, IjC301.java
Site : 백준
Title : 10989 / 수 정렬하기 3
Date : 19th July 2022 year
Subject : 배열
Site : 백준
Title : 1110 / 더하기 사이클
Date : 19th July 2022 year
Subject : 수학
Site : 인프런
Title : 2-11 / 임시반장 정하기
Date : 18th July 2022 year
Subject : 배열 …

[Week5] BoJ10989.java, BoJ1110.java, IjC211~IjC301.java

---

src/week5/yumi/BoJ7795.java

Create BoJ7795.java
Site : 백준
Title : 7795/ 먹을 것인가 먹힐 것인가
Date : 19th July 2022 year
Subject : Two pointers

[Week5] BoJ7795.java

---

src/week5/yumi/BoJ24499.java

Create BoJ24499.java
Site : 백준
Title : 24499 / blobyum
Date : 19th July 2022 year
Subject : sliding window

[Week5] BoJ24499.java

---

src/week5/soram/BOJ10989.java
src/week5/soram/BOJ1110.java
src/week5/soram/IjC304.java

220723 commit

---

src/week5/soram/IjC301.java
src/week5/soram/IjC302.java
src/week5/soram/IjC303.java
src/week5/soram/IjC304.java

220724 commit

---

src/week5/woojin/BoJ10989.java
src/week5/woojin/BoJ1110.java
src/week5/woojin/BoJ24499.java
src/week5/woojin/BoJ7795.java
src/week5/woojin/IjC0211.java

Title :  10989 / 수 정렬하기 3
Date : 24th July 2022 year
Level : bronze 1 
Subject : String
Title : 1110 / 더하기 사이클
Date : 24th July 2022 year
Level : bronze 1
Subject : 반복문
Title : 24499 / blobyum
Date : 24th July 2022 year
Level : silver 4
Subject : slicing window
Contents : This logic of my method and the side description of …

김우진 2022-07-24 5주차 과제 제출

---

src/week6/hong/BoJ2776.java

Title : 2776 / 암기왕
Date : Today (25th July 2022 year)
Level : Silver Ⅳ
Success or False :  ✔️ (Success)

[DC] Dilay Commit

---

src/week6/soram/BoJ2776.java
src/week6/soram/IjC305.java
src/week6/soram/IjC306.java
src/week6/soram/IjC401.java
src/week6/soram/IjC402.java

220729 commit

---

src/week6/yumi/BoJ15900.java
src/week6/yumi/BoJ1822.java
src/week6/yumi/BoJ9322.java
src/week6/yumi/BoJ9372.java
src/week6/yumi/IjC401.java
src/week6/yumi/IjC402.java
src/week6/yumi/IjC403.java
src/week6/yumi/IjC404.java
src/week6/yumi/PrG1845.java

Create PrG1845.java, BoJ15900.java, BoJ1822.java, BoJ9322.java. BoJ9372.java, IjC401.java, IjC402.java, IjC403.java
Site : 프로그래머스
Title : 1845 / 포켓몬
Date : 31th July 2022 year
Subject : HashMap, TreeSet
Site : 백준
Title : 15900  / 나무탈출
Date : 31th July 2022 year
Subject : HashMap, TreeSet
Site : 백준
Title : 9322 / 철벽 보안 알고리즘
Date : 31th July 2022 year
Subject : HashMap, TreeSet
Contents : This logic of my method and the side …

[Week6] PrG1845.java, BoJ15900.java, BoJ1822.java, IjC401.java ~ IjC403.java

---

src/week7/hong/BoJ11725.java
src/week7/hong/IjC404.java
src/week7/hong/IjC405.java

Create 037. 모든 아나그램 찾기.java
Title :   037. 모든 아나그램 찾기
Date : Today (2th August 2022 year)
Contents : Watch the video, these's two method
Create 038. K번째 큰 수.java
Title :  038. K번째 큰 수
Date : Today (3th August 2022 year)  
Contents : Watch the video, these's two method
Title : 11725 / 트리의 부모 찾기
Date : Today (04th August 2022 year)
Level : Silver Ⅱ
Success or False :  ❌ (Fasle)

[DC] Daily Commit push

---

src/week7/ram/BoJ11725.JAVA
src/week7/ram/BoJ1260.JAVA

220806 commit

---

src/week7/ram/BoJ1991.JAVA
src/week7/ram/notion.md

220806 2nd commit

---

src/week7/ram/BoJ2667.JAVA
src/week7/ram/IjC404.JAVA
src/week7/ram/IjC405.JAVA

220806 3rd commit

---

src/week7/yumi/BoJ11725.java
src/week7/yumi/BoJ11725_F.java
src/week7/yumi/BoJ1260.java
src/week7/yumi/BoJ1991.java
src/week7/yumi/BoJ2667.java

Create BoJ11725.java, BoJ1260.java, BoJ1991.java, BoJ2667.java
Site : 백준
Title : 11725 / 트리의 부모 찾기
Date : 7th August 2022 year
Subject : Tree
Success or False : :fire (Fail)
Site : 백준
Title : 1991 / 트리순회
Date : 7th August 2022 year
Subject : Tree
Site : 백준
Title : 1260 / DFS와 BFS
Date : 7th August 2022 year
Subject : DFS, BFS …

[Week7] BoJ11725.java, BoJ1260.java, BoJ1991.java, BoJ2667.java

---

src/week5/woojin/IjC0303.java
src/week6/woojin/BoJ9322.java
src/week6/woojin/IjC0401.java
src/week6/woojin/IjC0402.java
src/week6/woojin/IjC0403.java
src/week6/woojin/PrG1845.java
src/week7/woojin/BoJ11725.java
src/week7/woojin/BoJ1260.java
src/week7/woojin/BoJ1991.java
src/week7/woojin/BoJ2667.java

Title : 1991 / 트리 순회
Date : 7th Aug 2022
Level : silver 1  
Subject : tree, binary tree
Title : 11725 / 트리의 부모 찾기
Date : 7th Aug 2022
Level : silver 2  
Subject : tree, graph
Title : 1260 / DFS와 BFS
Date : 7th Aug 2022
Level : silver 2  
Subject : dfs, bfs …

[김우진] 7주차 BoJ 문제 제출

---

psStudy/src/week8/ram/BoJ1021.java
psStudy/src/week8/ram/BoJ1966.java
psStudy/src/week8/ram/BoJ3986.java
psStudy/src/week8/ram/IjC501.java
psStudy/src/week8/ram/IjC502.java
psStudy/src/week8/ram/IjC503.java
psStudy/src/week8/ram/IjC504.java
psStudy/src/week8/ram/IjC505.java
psStudy/src/week8/ram/IjC506.java

220813 commit

---

src/week8/ram/BoJ1021.JAVA
src/week8/ram/BoJ1966.JAVA
src/week8/ram/BoJ3986.JAVA
src/week8/ram/IjC501.java
src/week8/ram/IjC502.JAVA
src/week8/ram/IjC503.java
src/week8/ram/IjC504.JAVA
src/week8/ram/IjC505.JAVA
src/week8/ram/IjC506.JAVA

220814 commit

---

src/week9/yumi/BoJ11399.java
src/week9/yumi/BoJ2750.java
src/week9/yumi/BoJ2751.java
src/week9/yumi/IjC601.java
src/week9/yumi/IjC602.java
src/week9/yumi/IjC603.java
src/week9/yumi/PrG17686.java

Create BoJ11399.java, BoJ2750.java, BoJ2751.java, PrG17686.java, IjC601.java ~ IjC603.java
Site : 백준
Title : 11399 / ATM
Date : 21th August 2022 year
Subject : Sort
Site : 백준
Title : 2750 수 정렬하기
Date : 21th August 2022 year
Subject : Sort
Site : 백준
Title : 2751 수 정렬하기2
Date : 21th August 2022 year
Subject : Sort …

[Week9] BoJ11399.java, BoJ2750.java, BoJ2751.java, PrG17686.java,

---

src/week9/hong/BoJ11399.java
src/week9/hong/BoJ2750.java
src/week9/hong/BoJ2751.java

Title : 2750 / 수 정렬하기2
Date : Today (21th August 2022 year)
Level : Bronze II
Success or False :  ✔️ (Success)
==================================================
Title : 2751 / 수 정렬하기2
Date : Today (21th August 2022 year)
Level : Silver V
Success or False :  ✔️ (Success)
==================================================
Title : 11399 / ATM
Date : Today (21th August 2022 year)
Level : Silver IV
Success or False :  ✔️ (Success)

[DC] Dailay commit

---

src/week10/yumi/BoJ11729.java
src/week10/yumi/BoJ14501.java
src/week10/yumi/BoJ14889.java
src/week10/yumi/BoJ9934_F.java

Create BoJ14501.java, BoJ14889.java, BoJ11729.java, BoJ9012.java
Site : 백준
Title : 14501 / 퇴사
Date : 27th August 2022 year
Subject : DFS
Site : 백준
Title : 14889 / 스타트와 링크
Date : 27th August 2022 year
Subject : DFS
Site : 백준
Title : 11729 / 하노이 탑 이동 순서
Date : 27th August 2022 year
Subject : DFS …

[Week10] BoJ14501.java, BoJ14889.java, BoJ11729.java, BoJ9012.java

---

src/week10/woojin/BoJ14501.java
src/week10/woojin/BoJ14889.java
src/week10/woojin/BoJ9934.java

[김우진] 2022-08-28 week10 문제 제출

---

src/week10/hong/BoJ11729.java
src/week10/hong/BoJ14501.java
src/week10/hong/BoJ9934.java
src/week10/hong/IjC607.java
src/week10/hong/IjC608.java
src/week10/hong/IjC609.java
src/week10/hong/IjC610.java

Title :    이분검색
Date : Today (24th August 2022 year)  
Contents : Watch the video, these's two method
Title :    좌표 정렬
Date : Today (24th August 2022 year)  
Contents : Watch the video, these's two method
Title : 14501 / 퇴사
Date : Today (24th August 2022 year)
Level : Silver Ⅲ
Success or False :  ✔️ (Success)
Contents : 진짜 퇴사했음.
Title : 11729 / 하노이 탑 이동 순서
Date : Today (24th August 2022 year)
Level : Silver I
Success or False :  ✔️ (Success)
Title : 9934 / 완전 이진 트리
Date : Today (24th …

[DC]Dilay commit

---

src/week11/woojin/BoJ25416.java
src/week11/woojin/BoJ25511.java
src/week11/woojin/BoJ3184.java
src/week11/woojin/PrG1844.java

[김우진] 2022-09-04 week11 문제 제출

---

src/week11/ram/BoJ25416.JAVA
src/week11/ram/BoJ25511.JAVA
src/week11/ram/BoJ3184.JAVA
src/week11/ram/IjC704.java
src/week11/ram/IjC705.JAVA
src/week11/ram/IjC707.JAVA
src/week11/ram/IjC708.JAVA

220904 Commit

---

src/week12/yumi/BoJ1012.java
src/week12/yumi/BoJ1325.java
src/week12/yumi/BoJ2468.java
src/week12/yumi/BoJ2606.java

Create BoJ1012.java, BoJ1325.java, BoJ2468.java, BoJ2606.java
Site : 백준
Title : 1012 / 유기농 배추
Date : 18th September2022 year
Subject : DFS
Site : 백준
Title : 1325 / 효율적인 해킹
Date : 18th September2022 year
Subject : BFS
Site : 백준
Title : 2468 / 안전 영역
Date : 18th September2022 year
Subject : DFS …

[Week12] Create BoJ1012.java, BoJ1325.java, BoJ2468.java, BoJ2606.java

---

src/mobile/main.dart
src/mobile/pubspec.yaml
src/week13/ram/BoJ1946.JAVA
src/week13/ram/IjC901.java
src/week13/ram/IjC902.JAVA

220923 commit

---

src/week13/yumi/BoJ1026.java
src/week13/yumi/BoJ16953.java
src/week13/yumi/BoJ1946.java
src/week13/yumi/BoJ5585.java
src/week13/yumi/IjC901.java
src/week13/yumi/IjC902.java
src/week13/yumi/IjC903.java
src/week13/yumi/IjC904.java

Create BoJ16953.java, BoJ5585.java, BoJ1026.java, BoJ1946.java, IjC901.java, IjC902.java, IjC903.java, IjC904.java
Site : 백준
Title : 16953 / A → B
Date : 24th September2022 year
Subject : Greedy
Site : 백준
Title : 5585 거스름돈
Date : 24th September2022 year
Subject : Greedy
Site : 백준
Title : 1026 / 보물
Date : 25th September2022 year
Subject : Greedy
method …

[Week13] Create BoJ, IjC

---

src/week13/woojin/BoJ1026.java
src/week13/woojin/BoJ16953.java
src/week13/woojin/BoJ1946.java
src/week13/woojin/BoJ5585.java

[김우진] week13 과제 제출

---

src/week13/ram/BoJ16953.JAVA
src/week13/ram/BoJ5585.JAVA

220925 commit

---

src/week14/yumi/PrG17680.java
src/week14/yumi/PrG42842.java
src/week14/yumi/PrG64065.java

Create PrG64065.java, PrG17680.java, PrG42842.java
Site : 프로그래머스
Title : 64065 / 튜플
Date : 1th October 2022
Subject : comprehensive
Site : 프로그래머스
Title : 17680 / 캐시
Date : 1th October 2022
Subject : comprehensive
Site : 프로그래머스
Title : 42842 / 카펫
Date : 1th October 2022
Subject : comprehensive

[Week14] Create BoJ

---

src/week14/woojin/PrG_17680.java
src/week14/woojin/PrG_42842.java
src/week14/woojin/PrG_76502.java

[김우진] 2022-10-02 week14 문제 제출

---

src/week15/yumi/PrG12973.java
src/week15/yumi/PrG12985.java
src/week15/yumi/PrG42885.java
src/week15/yumi/PrG87946.java

Create PrG42885.java, PrG12985.java, PrG12973.java, PrG87946.java
Site : 프로그래머스
Title : 42885 / 구명보트
Date : 9th October 2022
Subject : comprehensive
Site : 프로그래머스
Title : 12985 / 예상 대진표
Date : 9th October 2022
Subject : comprehensive
Success or False : :fire (fail)
Site : 프로그래머스
Title : 12973 / 짝지어 제거하기
Date : 9th October 2022
Subject : comprehensive …

[Week15] PrG 과제 제출

---

src/week16/yumi/BoJ13305.java
src/week16/yumi/BoJ16493.java
src/week16/yumi/BoJ2225.java
src/week16/yumi/BoJ2579.java

Site : 백준
Title : 13305 / 주유소
Date : 30th October 2022
Subject : greedy
Success or False : :fire (Fail)
Site : 백준
Title : 16493 / 최대 페이지 수
Date : 30th October 2022
Subject : greedy
Success or False : :fire (Fail)
Site : 백준
Title : 2225 / 합분해
Date : 30th October 2022
Subject : dp
Site : 백준
Title : 2579 / 계단 오르기
Date : 30th October 2022
Subject : dp …

[Week16] 제출

---

src/week17/ram/BoJ12865.JAVA
src/week17/ram/BoJ2193.java
src/week17/ram/BoJ9465.JAVA

week17 commit

---

src/week17/yumi/BoJ12865.java
src/week17/yumi/BoJ2193.java
src/week17/yumi/BoJ9465.java
src/week17/yumi/BoJ9655.java

Site : 백준
Title : 2193 / 이친수
Date : 26th November 2022
Subject : dynamic programming
Success or False : :fire (Fail)
Site : 백준
Title : 9465 / 스티커
Date : 26th November 2022
Subject : dynamic programming
Site : 백준
Title : 9655 돌 게임
Date : 26th November 2022
Subject : dynamic programming
Site : 백준
Title : 12865 / 평범한 배낭 …

[Week17] 제출

---

src/week18/woojin/BoJ1261.java
src/week18/woojin/BoJ13913.java
src/week18/woojin/BoJ2178.java
src/week18/woojin/PrG43165.java

[김우진] 2022-12-04 week18 문제 제출

---

src/week19/ram/BoJ12761.JAVA
src/week19/ram/PrG12978.JAVA
src/week19/ram/PrG84021.JAVA

week19 commit

---

src/week19/woojin/BoJ12761.java
src/week19/woojin/PrG12978.java
src/week19/woojin/PrG81302.java

[김우진] 2022-12-11 week19 문제 제출
